In [1]:
# NumPy 별치 만들기, 간단한 배열 연산
import numpy as np

print(np.__version__)

1.26.2


In [2]:
mid_scores = np.array([10, 20, 30])
final_scores = np.array([60, 70, 80])
total = mid_scores + final_scores
print('시험성적 합계:', total) # 각 요소별 합계
print('시험성적 평균:', total/2) # 모든 요소 2로 나눔

시험성적 합계: [ 70  90 110]
시험성적 평균: [35. 45. 55.]


In [3]:
a = np.array([1,2,3,]) # 넘파이 ndarray 객체의 생성

# a 객체의 형태(shape)
# shape: 배열의 차원으로 (m, n) 형식의 튜플형. m과 n은 각 차원의 원소 크기 알려주는 정수
print(a.shape)

# a 객체의 차원(ndim)
# ndim: 배열 축 혹은 차원의 개수
print(a.ndim)

# a 객체 내부 자료형(dtype)
print(a.dtype) # dtype('int32')

# a 객체 내부 자료형이 차지하는 메모리 크기(byte)
print(a.itemsize)

# a 객체의 전체 크기(항목의 수)
print(a.size)


(3,)
1
int32
4
3


- N(1,2,3)D array

In [4]:
# 1. 0에서 9까지의 정수 값을 가지는 ndarray 객체 array_a를 넘파이를 이용하여 작성 출력
array_a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("실습1: array_a=", array_a)

실습1: array_a= [0 1 2 3 4 5 6 7 8 9]


In [5]:
# 2. range() 함수를 사용하여 0에서 9까지 정수 값을 가지는 ndarray 객체 array_b를 만들고 결과
array_b = np.array(range(10))
print("실습2: array_b=", array_b)

실습2: array_b= [0 1 2 3 4 5 6 7 8 9]


In [7]:
# 3. 문제 2의 코드를 수정하여 0에서 9까지의 정수 값 중에서 다음과 같이 짝수를 가지는 ndarray객체 array_c를 생성
array_c = np.array(range(0,10,2))
print("실습3: array_c=", array_c)

실습3: array_c= [0 2 4 6 8]


In [11]:
# 4. array_c의 shape, ndim, dtype, size, itemsize를 출력
print("실습4: ")
print("array_c의 shape:", array_c.shape)
print("array_c의 ndim:", array_c.ndim)
print("array_c의 dtype:", array_c.dtype)
print("array_c의 size:", array_c.size)
print("array_c의 itemsize:", array_c.itemsize)

실습4: 
array_c의 shape: (5,)
array_c의 ndim: 1
array_c의 dtype: int32
array_c의 size: 5
array_c의 itemsize: 4


In [14]:
# NumPy 배열 연산
salary = np.array([220, 250, 230])
salary = salary + 100 # NumPy 배열 저장된 모든 값 덧셈
print(salary)
salary = salary * 2 # NumPy 배열 저장된 모든 값 곱셈
print(salary)
salary = salary * 1.1 # NumPy 배열 저장된 모든 값 실수 적용 가능
print(salary)

[320 350 330]
[640 700 660]
[704. 770. 726.]


In [15]:
# NumPy 배열 연산
# 각 배열마다 타입이 하나만 있다고 생각
# 넘파이의 배열 안에는 동일한 타입의 데이터만 저장할 수 있다.(정수면 정수, 실수면 술수만 저장)
# 여러가지 타입을 섞어 배열에 전달하면 이것을 전부 문자열로 변경
tangled = np.array([100, 'test', 3.0, False])
print(tangled)
# 동일한 자료형으로만 데이터를 저장하면 각각의 데이터 항목에 필요한 저장공간 일정
# 몇 번째 위치에 있는 항목이든 그 순서만 알면 바로 접근 가능하기에 바르게 데이터 활용
# 원하는 위치에 바로 접근하여 데이터를 쓴느 일을 임의접근(random access)

['100' 'test' '3.0' 'False']


In [22]:
heights = [1.83, 1.76, 1.69, 1.86, 1.77, 1.73]
weights = [86, 74, 59, 95, 80, 68]

# print(type(heights)) #<class 'list'>
np_heights = np.array(heights)
np_weights = np.array(weights)

print("대상자들의 키:", np_heights)
print("대상자들의 몸무게:", np_weights)

bmi = np_weights / (np_heights**2)
print(f"대상자들의 BMI\n{bmi}")

대상자들의 키: [1.83 1.76 1.69 1.86 1.77 1.73]
대상자들의 몸무게: [86 74 59 95 80 68]
대상자들의 BMI
[25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]


- 인덱싱(Indexing)과 슬라이싱(Slicing)

In [27]:
scores = np.array([88, 72, 93, 94, 89, 78, 99])
print(scores[2])
print(scores[-1])
print(scores[1:4])
print(scores[3:])
print(scores[4:-1])

93
99
[72 93 94]
[94 89 78 99]
[89 78]


In [30]:
# 논리적 인덱싱
ages = np.array([18, 19, 25, 30, 28])
y = ages > 20
print(y, type(ages)) # 부울형으로 반환
print(ages[ages>20]) # 배열 형식으로 반환(부울형 배열을 인덱스로 하는 방법)

[False False  True  True  True] <class 'numpy.ndarray'>
[25 30 28]


In [31]:
# BMI 25가 넘는 사람만 추출하기
heights = [1.83, 1.76, 1.69, 1.86, 1.77, 1.73]
weights = [86, 74, 59, 95, 80, 68]
np_heights = np.array(heights)
np_weights = np.array(weights)
bmi = np_weights / (np_heights**2)
print(f"대상자들의 BMI(25이상)\n{bmi[bmi > 25]}")

대상자들의 BMI(25이상)
[25.68007405 27.45982194 25.53544639]


- 2차원 배열의 인덱싱

In [37]:
# 2차원 배열 -> 리스트의 리스트
y = [[1,2,3],[4,5,6],[7,8,9]]
np_array = np.array(y) # 2차원 배열(넘파이 다차원 배열)
print(np_array) # 역행렬이나 행렬식을 구하는 등의 행렬 연산들 적용 구현 수월

# 2차원 배열 인덱싱
print(np_array[0][2])
print(np_array[2][-1])
print(np_array[0, 0], np_array[0, 2])
# 파이썬 리스트와 달리 넘파이 배열은 모든 항목이 동일한 자료형을 가지기 때문에
# 정수 배열에서 부동 소수점 값 삽입하려고 시도해도 소수점 이하 값은 자동으로 사라짐
np_array[2,2] = 1.234
print(np_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
9
1 3
[[1 2 3]
 [4 5 6]
 [7 8 1]]


In [62]:
# 넘파이 스타일의 2차원 배열 잘라내기
np_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(np_array[0:2, 2:4])
print(np_array[1:4, 0:3])
print(np_array[0])
print(np_array[1, 1:3])

## 문제 (중요) ##
# 첫 슬라이싱: 0행, 2행 선택, 두번째 슬라이싱: 그 중 0행 선택
print(f"\n\n문제1)\n{np_array[::2][::2]}\n\n")
# 행 슬라이싱: 0행, 2행 선택, 열 슬라이싱: 0열 2열 선택
print(f"문제2)\n{np_array[::2,::2]}\n\n")


[[3 4]
 [7 8]]
[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[1 2 3 4]
[6 7]


문제1)
[[1 2 3 4]]


문제2)
[[ 1  3]
 [ 9 11]]




In [74]:
# 2차원 배열 논리적인 인덱싱
np_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np_array > 5)
print(np_array[np_array > 5])
print(np_array[:, 2])
print(np_array[:, 2] > 5)

print("\n",np_array[:] % 2 == 0)
print(np_array[np_array % 2 ==0])

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[3 6 9]
[False  True  True]

 [[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


- 2차원 배열 연습하기

In [83]:
# 문자 데이터를 저장하고 있는 어떤 2차원 넘파이 배열 x에서 'c' 문자가 몇 개 있는지
# 알고 싶을 때, 'c'만을 추출하여 배열을 만들자
x = np.array([['a','b','c','d'],['c','c','g','h']])
print(f"'c'의 문자 수: {x[x == 'c'].size}")

# 두개의 2차원 배열에 정수를 담아 두 배열을 차이 결과를 확인
mat_a = np.array([[10,20,30],[10,20,30]])
mat_b = np.array([[2,2,2],[1,2,3]])
print(f"두 NumPy 2차원 배열 차이 확인: \n{mat_a - mat_b}")

'c'의 문자 수: 3
두 NumPy 2차원 배열 차이 확인: 
[[ 8 18 28]
 [ 9 18 27]]


- Boolean Indexing

In [105]:
# 데모 배열 생성
a1 = np.arange(1, 25).reshape((4,6)) # 2차원 배열
# print(a1)
# print(f"a1 배열의 짝수 요소 집합: \n{a1[a1 % 2 == 0]}")

# 짝수 요소 확인
# numpy broad casting을 이용하여 짝수인 배열 요소 확인
even_arr = a1 % 2 == 0
print(type(even_arr))
print(f"shape: {even_arr.shape}, dimension: {even_arr.ndim}, dtype:{even_arr.dtype}")
print(f"Array's Data:\n{even_arr}")
print(a1[even_arr])
print(np.sum(a1))

<class 'numpy.ndarray'>
shape: (4, 6), dimension: 2, dtype:bool
Array's Data:
[[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]]
[ 2  4  6  8 10 12 14 16 18 20 22 24]
300


- Fancy Indexing

In [114]:
# 배열에 인덱스 배열을 전달하여 요소를 참조하는 방법
arr = np.arange(1,25).reshape((4,6))
print(arr, "\n")

# Facncy Case1
print([arr[0,0], arr[1,1], arr[2,2], arr[3,3]], "\n")

# Facncy Case2
print(arr[:, [1,2]])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]] 

[1, 8, 15, 22] 

[[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]]


- 넘파이 배열의 형태 알아내고 슬라이싱 연산(문제)

In [118]:
# 검사 대상들의 키와 몸무게 2차원 넘파이 배열로 저장되어 있을 때 결과 값 확인
import numpy as np

x = np.array([[1.83, 1.76, 1.69, 1.86, 1.77, 1.73], [86.0, 74.0, 59.0, 95.0, 80.0, 68.0]])
y = x[0:2, 1:3] # [[1.76  1.69] [74. 59.]]
z = x[0:2][1:3] # [[86. 74. 59. 95. 80. 68.]]

print('x shape :', x.shape)
print('y shape :', y.shape)
print('z shape :', z.shape)
print('z values :', z)

bmi = x[0] / x[1]**2
print('BMI data')
print(bmi)

x shape : (2, 6)
y shape : (2, 2)
z shape : (1, 6)
z values : [[86. 74. 59. 95. 80. 68.]]
BMI data
[0.00024743 0.0003214  0.00048549 0.00020609 0.00027656 0.00037413]


In [121]:
# 2차원 배열에서 특정 조건을 만족하는 행만 추출하기
players = [[170, 76.4], [183, 86.2], [181, 78.5], [176, 80.1]]
np_players = np.array(players)

print('몸무게 80 이상인 선수 정보')
print(np_players[np_players[:, 1] >= 80.0]) # 선수들 가운데 80 넘는 선수만 고른 정보

print('키가 180 이상인 선수 정보')
print(np_players[np_players[:, 0] >= 180]) # 키가 180이상인 선수들 정보 추출

몸무게 80 이상인 선수 정보
[[183.   86.2]
 [176.   80.1]]
키가 180 이상인 선수 정보
[[183.   86.2]
 [181.   78.5]]


- ndarray 생성

In [127]:
# zeros((n,m)): n * m 배열(혹은 행렬)을 생성해서 초기값 0
# eye(n): n * n 크기의 단위행렬 identity matrix을 생성
    # 정방행렬 중에서 대각선 성분이 1이고 나머지 성분이 0인 행렬
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.full((2,3), 100))
print(np.eye(3))
print(np.random.random((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[100 100 100]
 [100 100 100]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.66903144 0.84941142 0.24462338]
 [0.35177993 0.45898642 0.22232438]]


- arange() 함수

In [145]:
print(np.arange(0,10))
print(np.arange(0,10,2))
print(np.arange(0,10,3))
print(np.arange(0.0, 1.0, 0.2))
# linspace()함수 - 동일한 간격을 가진 연속된 값 생성 (시작, 끝, 간격의 수)
print(np.linspace(0, 10, 5))
print(np.linspace(0, 10, 4))

# 파이썬 리스트는 실수 값을 사용할 수 없음.
# a = list(range(1, 10, 0.5))
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 3 6 9]
[0.  0.2 0.4 0.6 0.8]
[ 0.   2.5  5.   7.5 10. ]
[ 0.          3.33333333  6.66666667 10.        ]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


- arange()함수와 range()함수

In [154]:
# 시작 값을 지정
print(np.arange(1,6))
# 증가되는 값을 지정
print(np.arange(1, 10, 2))
print(list(range(5)))
print(list(range(0,5,2)))

# range()를 써서 arange()와 같이 넘파이 배열 만들기
print(np.array(range(1,6)))

[1 2 3 4 5]
[1 3 5 7 9]
[0, 1, 2, 3, 4]
[0, 2, 4]
[1 2 3 4 5]


- linspace()함수와 logspace()함수

In [ ]:
# linspace(): 시작값부터 끝값까지 균일한 간격으로 지정된 개수만큼 배열생성
# numpy.linspace(start, stop, num=50)
# 1. 데이터 생성을 시작할 값 - 생략 가능
# 2. 데이터 생성을 멈출 값 - 생략 가능(stop-1이 아니라 stop까지 생성됨)
# 3. 데이터 생성 개수 - 기본값은 50개

# logspace(): 로그 스케일로 수들을 생성
# numpy.logspace(start, stop, num=50)
# 1. 데이터 생성을 10^start부터 시작
# 2. 데이터 생성을 10^stop까지
# 3. 데이터 생성 개수 - 기분값은 50개